services:
  java-eladmin-system:
    build:
      context: ./eladmin/eladmin-system
    container_name: java-eladmin-system
    restart: unless-stopped
    init: true
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - eladmin-net
    ports:
      - "8080:8080"  # Spring Boot API
    # env_file: ./.env  # Uncomment if .env file exists in eladmin-system

  js-eladmin-web:
    build:
      context: ./eladmin-web
    container_name: js-eladmin-web
    restart: unless-stopped
    init: true
    depends_on:
      - java-eladmin-system
    networks:
      - eladmin-net
    ports:
      - "8013:8013"  # Vue.js static web app
    # env_file: ./.env  # Uncomment if .env file exists in eladmin-web

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    networks:
      - eladmin-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: eladmin
      MYSQL_DATABASE: eladmin
      MYSQL_USER: eladmin
      MYSQL_PASSWORD: eladmin
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-config/my.cnf:/etc/mysql/my.cnf:ro
      - ./sql/eladmin.sql:/docker-entrypoint-initdb.d/eladmin.sql:ro
      - ./sql/quartz.sql:/docker-entrypoint-initdb.d/quartz.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - eladmin-net
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  eladmin-net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
